/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example;

import javafx.application.Application;
import javafx.fxml.FXMLLoader;
import javafx.scene.Parent;
import javafx.scene.Scene;
import javafx.stage.Stage;


/**
 * Entry point JavaFX dell'applicazione.
 * Carica la vista FXML principale e mostra la finestra della battaglia.
 */
public class App extends Application {
    @Override
    public void start(Stage primaryStage) throws Exception {
       FXMLLoader loader = new FXMLLoader(getClass().getResource("/org/example/vista.fxml"));
       Parent root = loader.load();

       Scene scene = new Scene(root);

       primaryStage.setScene(scene);
       primaryStage.show();
    }

    public static void main(String[] args) {
        launch(args);
    }
}
